
/*CREATE USER c##cono
IDENTIFIED BY cono;

GRANT CONNECT, RESOURCE TO c##cono;*/

-- 테이블 삭제
DROP TABLE SHAREREPLY CASCADE CONSTRAINTS;
DROP TABLE DAILYREPLY CASCADE CONSTRAINTS;
DROP TABLE QUESTIONREPLY CASCADE CONSTRAINTS;
DROP TABLE DIARYREPLY CASCADE CONSTRAINTS;
DROP TABLE INFOSHARE CASCADE CONSTRAINTS;
DROP TABLE DAILY CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE DIARY CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE CONTEST CASCADE CONSTRAINTS;
DROP TABLE DOG CASCADE CONSTRAINTS;
DROP TABLE CAREBOARD CASCADE CONSTRAINTS;
DROP TABLE PLACEBOARD CASCADE CONSTRAINTS;
DROP TABLE QUIZ CASCADE CONSTRAINTS;
DROP TABLE SHOP CASCADE CONSTRAINTS;
DROP TABLE CAREREPLY CASCADE CONSTRAINTS;
DROP TABLE PLACEREPLY CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL CASCADE CONSTRAINTS;
DROP TABLE FUNERAL CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP TABLE CAFE CASCADE CONSTRAINTS;
DROP TABLE HAIRSHOP CASCADE CONSTRAINTS;
DROP TABLE TRAINNING CASCADE CONSTRAINTS;
DROP TABLE GUESTHOUSE CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS;


-- 1. 애견정보 테이블
CREATE TABLE DOG(
DOG_TYPE VARCHAR2(30),
DOG_SIZE VARCHAR2(30) NOT NULL,
DOG_HAIR VARCHAR2(30) NOT NULL,
DOG_STAMINA VARCHAR2(30) NOT NULL,
DOG_CHAR VARCHAR2(30) NOT NULL,
DOG_LOC VARCHAR2(30) NOT NULL,
DOG_IMG VARCHAR2(30) NOT NULL,
DOG_INFO VARCHAR2(200) NOT NULL,

CONSTRAINT PK_DOG PRIMARY KEY (DOG_TYPE)
);
-- 애견정보 테이블 코멘트
COMMENT ON TABLE DOG IS '애견정보';
COMMENT ON COLUMN DOG.DOG_TYPE IS '품종';
COMMENT ON COLUMN DOG.DOG_SIZE IS '크기';
COMMENT ON COLUMN DOG.DOG_HAIR IS '털빠짐';
COMMENT ON COLUMN DOG.DOG_STAMINA IS '활동량';
COMMENT ON COLUMN DOG.DOG_CHAR IS '성격';
COMMENT ON COLUMN DOG.DOG_LOC IS '원산지';
COMMENT ON COLUMN DOG.DOG_IMG IS '이미지';
COMMENT ON COLUMN DOG.DOG_INFO IS '상세정보';
insert into DOG values ('프렌치불독', '소형', '털잘빠짐', '활발함', '괴팍함', '미국', '1', '11');

-- 2. 회원 테이블
CREATE TABLE MEMBER (
USER_NAME VARCHAR2(30) NOT NULL,
USER_NICK VARCHAR2(30) NOT NULL,
USER_ID VARCHAR2(30),
USER_PWD VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(30),
BIRTH VARCHAR2(8) NOT NULL,
GENDER CHAR(1) NOT NULL,
USER_PICTURE VARCHAR2(30),
USER_PICTURE_RENAME VARCHAR2(30),
DOG_NAME VARCHAR2(30),
DOG_BIRTH VARCHAR2(8),
DOG_TYPE  VARCHAR2(30),
DOG_GENDER CHAR(1),
USER_ADMIN CHAR(1) DEFAULT 'N',
LOGIN_LIMIT CHAR(1) DEFAULT 'Y',

CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
CONSTRAINT FK_DOG_TYPE FOREIGN KEY (DOG_TYPE) REFERENCES DOG,
CONSTRAINT CHK_USER_ADMIN CHECK (USER_ADMIN IN ('Y', 'N')),
CONSTRAINT CHK_LOGIN_LIMIT CHECK (LOGIN_LIMIT IN ('Y', 'N'))
);
-- 회원 테이블 코멘트
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.USER_NICK IS '회원 닉네임';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.USER_PICTURE IS '프로필사진';
COMMENT ON COLUMN MEMBER.USER_PICTURE_RENAME IS '프로필사진수정파일';
COMMENT ON COLUMN MEMBER.DOG_NAME IS '반려견 이름';
COMMENT ON COLUMN MEMBER.DOG_BIRTH IS '반려견 생년월일';
COMMENT ON COLUMN MEMBER.DOG_TYPE IS '반려견 종';
COMMENT ON COLUMN MEMBER.DOG_GENDER IS '반려견 성별';
COMMENT ON COLUMN MEMBER.USER_ADMIN IS '관리자 여부';
COMMENT ON COLUMN MEMBER.LOGIN_LIMIT IS '로그인 제한';
insert into member  values('홍길동', '길동', 'user01', 'pass01', 'gildong12@google.com','19950715', 'M', NULL, NULL, '초코', '20220122', '프렌치불독', 'M', DEFAULT , DEFAULT );
insert into member  values('관리자', '관리자', 'admin', 'admin', 'admin@google.com','19950715', 'M', NULL, NULL, '민국이', '20220122', '프렌치불독', 'M', 'Y', DEFAULT );

-- 3. 샵 테이블
CREATE TABLE SHOP(
SITE_NAME VARCHAR2(30),
SITE_URL VARCHAR2(100) NOT NULL,
SITE_IMAGE VARCHAR2(30) NOT NULL,

CONSTRAINT PK_SITE_NAME PRIMARY KEY (SITE_NAME)
);
-- 샵 테이블 코멘트
COMMENT ON TABLE SHOP IS '샵';
COMMENT ON COLUMN SHOP.SITE_NAME IS '홈페이지 이름';
COMMENT ON COLUMN SHOP.SITE_URL IS '홈페이지 주소';
COMMENT ON COLUMN SHOP.SITE_IMAGE IS '홈페이지 이미지';

-- 4. 퀴즈 테이블
CREATE TABLE QUIZ(
USER_ID VARCHAR2(30),
QUIZ_NO NUMBER,
QUIZ VARCHAR2(100) NOT NULL,
QUIZ_RIGHT VARCHAR2(30) NOT NULL,
QUIZ_EXPLAIN VARCHAR2(300) NOT NULL,
QUIZ_DATE DATE DEFAULT SYSDATE,
QUIZ_COUNT NUMBER,
LIKE_COUNT NUMBER,
RANDOMQUIZ CHAR(1) DEFAULT '0',

CONSTRAINT PK_QUIZ_NO PRIMARY KEY (QUIZ_NO),
CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES MEMBER,
CONSTRAINT CHK_RANDOMQUIZ CHECK (RANDOMQUIZ IN ('0', '1'))
);
-- 퀴즈 테이블 코멘트
COMMENT ON TABLE QUIZ IS '퀴즈';
COMMENT ON COLUMN QUIZ.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN QUIZ.QUIZ_NO IS '퀴즈 게시판 번호';
COMMENT ON COLUMN QUIZ.QUIZ IS '퀴즈 질문';
COMMENT ON COLUMN QUIZ.QUIZ_RIGHT IS '퀴즈 정답';
COMMENT ON COLUMN QUIZ.QUIZ_EXPLAIN IS '퀴즈 설명';
COMMENT ON COLUMN QUIZ.QUIZ_DATE IS '작성 날짜';
COMMENT ON COLUMN QUIZ.QUIZ_COUNT IS '조회수';
COMMENT ON COLUMN QUIZ.LIKE_COUNT IS '좋아요 표시';
COMMENT ON COLUMN QUIZ.RANDOMQUIZ IS '랜덤퀴즈 등록여부';

-- 5. CARE 게시판
CREATE TABLE CAREBOARD(
CATEGORY VARCHAR2(20) NOT NULL,
USER_ID VARCHAR2(30),
LOCATION VARCHAR2(20) NOT NULL,
BOARD_NO NUMBER,
BOARD_TITLE VARCHAR2(50) NOT NULL,
BOARD_CONTENT VARCHAR2(100) NOT NULL,
BOARD_DATE DATE DEFAULT SYSDATE,
BOARD_COUNT NUMBER DEFAULT 0,
IMAGE VARCHAR2(30),
NEW_IMAGE VARCHAR2(30),
STAR_POINT NUMBER DEFAULT 0,

CONSTRAINT PK_CARE_NO PRIMARY KEY (BOARD_NO),
FOREIGN KEY (USER_ID) REFERENCES MEMBER
);

COMMENT ON TABLE CAREBOARD IS 'CARE 게시판';
COMMENT ON COLUMN CAREBOARD.CATEGORY IS '카테고리';
COMMENT ON COLUMN CAREBOARD.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN CAREBOARD.LOCATION IS '지역';
COMMENT ON COLUMN CAREBOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN CAREBOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN CAREBOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN CAREBOARD.BOARD_DATE IS '작성 날짜';
COMMENT ON COLUMN CAREBOARD.BOARD_COUNT IS '조회수';
COMMENT ON COLUMN CAREBOARD.IMAGE IS '첨부이미지';
COMMENT ON COLUMN CAREBOARD.NEW_IMAGE IS '수정이미지';
COMMENT ON COLUMN CAREBOARD.STAR_POINT IS '별점';

-- 6. PLACE 게시판
CREATE TABLE PLACEBOARD(
CATEGORY VARCHAR2(20) NOT NULL,
USER_ID VARCHAR2(30),
LOCATION VARCHAR2(20) NOT NULL,
BOARD_NO NUMBER,
BOARD_TITLE VARCHAR2(50) NOT NULL,
BOARD_CONTENT VARCHAR2(100) NOT NULL,
BOARD_DATE DATE DEFAULT SYSDATE,
BOARD_COUNT NUMBER DEFAULT 0,
IMAGE VARCHAR2(30),
NEW_IMAGE VARCHAR2(30),
STAR_POINT NUMBER DEFAULT 0,

CONSTRAINT PK_PLACE_NO PRIMARY KEY(BOARD_NO),
FOREIGN KEY (USER_ID) REFERENCES MEMBER
);

COMMENT ON TABLE PLACEBOARD IS 'PLACE 게시판';
COMMENT ON COLUMN PLACEBOARD.CATEGORY IS '카테고리';
COMMENT ON COLUMN PLACEBOARD.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN PLACEBOARD.LOCATION IS '지역';
COMMENT ON COLUMN PLACEBOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN PLACEBOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN PLACEBOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN PLACEBOARD.BOARD_DATE IS '작성 날짜';
COMMENT ON COLUMN PLACEBOARD.BOARD_COUNT IS '조회수';
COMMENT ON COLUMN PLACEBOARD.IMAGE IS '첨부이미지';
COMMENT ON COLUMN PLACEBOARD.NEW_IMAGE IS '수정이미지';
COMMENT ON COLUMN PLACEBOARD.STAR_POINT IS '별점';

-- 7.  CARE 댓글
CREATE TABLE CAREREPLY(
REP_NO NUMBER,
BOARD_NO NUMBER,
REP_WRITER VARCHAR2(30),
REP_CONTENT VARCHAR2(100),
REP_DATE DATE,

CONSTRAINT PK_CARE_REP_NO PRIMARY KEY(REP_NO),
CONSTRAINT FK_CARE_NO FOREIGN KEY (BOARD_NO) REFERENCES CAREBOARD,
CONSTRAINT FK_CARE_WRITER FOREIGN KEY (REP_WRITER) REFERENCES MEMBER (USER_ID)
);
COMMENT ON TABLE CAREREPLY IS '댓글_CARE';
COMMENT ON COLUMN CAREREPLY.REP_NO IS '댓글번호';
COMMENT ON COLUMN CAREREPLY.BOARD_NO IS '원글번호';
COMMENT ON COLUMN CAREREPLY.REP_WRITER IS '댓글작성자';
COMMENT ON COLUMN CAREREPLY.REP_CONTENT IS '댓글내용';
COMMENT ON COLUMN CAREREPLY.REP_DATE IS '댓글날짜';

-- 8. PLACE 댓글
CREATE TABLE PLACEREPLY(
REP_NO NUMBER,
BOARD_NO NUMBER,
REP_WRITER VARCHAR2(30),
REP_CONTENT VARCHAR2(100),
REP_DATE DATE,

CONSTRAINT PK_PLACE_REP_NO PRIMARY KEY(REP_NO),
CONSTRAINT FK_PLACE_NO FOREIGN KEY (BOARD_NO) REFERENCES PLACEBOARD,
CONSTRAINT FK_PLACE_WRITER FOREIGN KEY (REP_WRITER) REFERENCES MEMBER (USER_ID)
);
COMMENT ON TABLE PLACEREPLY IS '댓글_PLACE';
COMMENT ON COLUMN PLACEREPLY.REP_NO IS '댓글번호';
COMMENT ON COLUMN PLACEREPLY.BOARD_NO IS '원글번호';
COMMENT ON COLUMN PLACEREPLY.REP_WRITER IS '댓글작성자';
COMMENT ON COLUMN PLACEREPLY.REP_CONTENT IS '댓글내용';
COMMENT ON COLUMN PLACEREPLY.REP_DATE IS '댓글날짜';

-- 9. 동물병원 위치
CREATE TABLE HOSPITAL(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);
COMMENT ON TABLE HOSPITAL IS '동물병원 위치';
COMMENT ON COLUMN HOSPITAL.NAME IS '동물병원명';
COMMENT ON COLUMN HOSPITAL.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN HOSPITAL.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN HOSPITAL.PHONE IS '전화번호';
COMMENT ON COLUMN HOSPITAL.LATITUDE IS '위도';
COMMENT ON COLUMN HOSPITAL.LONGITUDE IS '경도';

-- 10. 장례업체 위치
CREATE TABLE FUNERAL(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE FUNERAL IS '장례업체 위치';
COMMENT ON COLUMN FUNERAL.NAME IS '장례업체명';
COMMENT ON COLUMN FUNERAL.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN FUNERAL.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN FUNERAL.PHONE IS '전화번호';
COMMENT ON COLUMN FUNERAL.LATITUDE IS '위도';
COMMENT ON COLUMN FUNERAL.LONGITUDE IS '경도';

-- 11. 애견호텔 위치
CREATE TABLE HOTEL(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE HOTEL IS '애견호텔 위치';
COMMENT ON COLUMN HOTEL.NAME IS '애견호텔명';
COMMENT ON COLUMN HOTEL.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN HOTEL.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN HOTEL.PHONE IS '전화번호';
COMMENT ON COLUMN HOTEL.LATITUDE IS '위도';
COMMENT ON COLUMN HOTEL.LONGITUDE IS '경도';

-- 12. 애견동반카페 위치
CREATE TABLE CAFE(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE CAFE IS '애견동반카페 위치';
COMMENT ON COLUMN CAFE.NAME IS '애견동반카페';
COMMENT ON COLUMN CAFE.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN CAFE.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN CAFE.PHONE IS '전화번호';
COMMENT ON COLUMN CAFE.LATITUDE IS '위도';
COMMENT ON COLUMN CAFE.LONGITUDE IS '경도';

-- 13. 미용업체 위치
CREATE TABLE HAIRSHOP(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE HAIRSHOP IS '미용업체 위치';
COMMENT ON COLUMN HAIRSHOP.NAME IS '미용업체명';
COMMENT ON COLUMN HAIRSHOP.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN HAIRSHOP.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN HAIRSHOP.PHONE IS '전화번호';
COMMENT ON COLUMN HAIRSHOP.LATITUDE IS '위도';
COMMENT ON COLUMN HAIRSHOP.LONGITUDE IS '경도';

-- 14. 애견훈련소 위치
CREATE TABLE TRAINNING(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE TRAINNING IS '애견훈련소 위치';
COMMENT ON COLUMN TRAINNING.NAME IS '애견훈련소명';
COMMENT ON COLUMN TRAINNING.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN TRAINNING.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN TRAINNING.PHONE IS '전화번호';
COMMENT ON COLUMN TRAINNING.LATITUDE IS '위도';
COMMENT ON COLUMN TRAINNING.LONGITUDE IS '경도';

-- 15. 애견동반숙소 위치
CREATE TABLE GUESTHOUSE(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE GUESTHOUSE IS '동물병원 위치';
COMMENT ON COLUMN GUESTHOUSE.NAME IS '동물병원명';
COMMENT ON COLUMN GUESTHOUSE.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN GUESTHOUSE.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN GUESTHOUSE.PHONE IS '전화번호';
COMMENT ON COLUMN GUESTHOUSE.LATITUDE IS '위도';
COMMENT ON COLUMN GUESTHOUSE.LONGITUDE IS '경도';

-- 16. 애견동반음식점 위치
CREATE TABLE RESTAURANT(
NAME VARCHAR2(100),
ADDRESS VARCHAR2(500),
ADDRESS2 VARCHAR2(500),
PHONE VARCHAR2(14),
LATITUDE VARCHAR2(200),
LONGITUDE VARCHAR2(200)
);

COMMENT ON TABLE RESTAURANT IS '애견동반음식점 위치';
COMMENT ON COLUMN RESTAURANT.NAME IS '애견동반음식점명';
COMMENT ON COLUMN RESTAURANT.ADDRESS IS '소재지 주소';
COMMENT ON COLUMN RESTAURANT.ADDRESS2 IS '도로명 주소';
COMMENT ON COLUMN RESTAURANT.PHONE IS '전화번호';
COMMENT ON COLUMN RESTAURANT.LATITUDE IS '위도';
COMMENT ON COLUMN RESTAURANT.LONGITUDE IS '경도';

-- 17. 커뮤니티 게시판_정보공유 테이블 생성
CREATE TABLE  INFOSHARE(
 BOARD_NO NUMBER, 
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_WRITER VARCHAR2(30) NOT NULL,
 BOARD_CONTENT VARCHAR2(2000) NOT NULL,
 BOARD_OLD_FILE VARCHAR2(100),
 BOARD_NEW_FILE VARCHAR2(100),
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER DEFAULT 0,
 LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,

  CONSTRAINT PK_INFOSHARE_NO PRIMARY KEY (BOARD_NO),
  CONSTRAINT FK_INFOSHARE_WRITER FOREIGN KEY (BOARD_WRITER)
  REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

--  커뮤니티 게시판_정보공유 컬럼코멘트 생성
COMMENT ON COLUMN INFOSHARE.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN INFOSHARE.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN INFOSHARE.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN INFOSHARE.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN INFOSHARE.BOARD_OLD_FILE IS '원본첨부파일명';
COMMENT ON COLUMN INFOSHARE.BOARD_NEW_FILE IS '수정첨부파일명';
COMMENT ON COLUMN INFOSHARE.BOARD_DATE IS '작성일자';
COMMENT ON COLUMN INFOSHARE.BOARD_COUNT IS '게시판조회수';
COMMENT ON COLUMN INFOSHARE.LIKE_COUNT IS '좋아요갯수';


-- 18. 댓글_정보공유 테이블 생성
CREATE TABLE SHAREREPLY (
 REF_NO NUMBER , 
BOARD_NO NUMBER NOT NULL,
REF_WRITER VARCHAR2(30) NOT NULL,
REF_CONTENT VARCHAR2(2000) NOT NULL,
REF_DATE DATE DEFAULT SYSDATE,

CONSTRAINT PK_SHAREREPLY_NO PRIMARY KEY (REF_NO),
CONSTRAINT FK_SHAREREPLY_NO FOREIGN KEY (BOARD_NO) 
REFERENCES INFOSHARE (BOARD_NO) ON DELETE SET NULL,
CONSTRAINT FK_SREF_WRITER FOREIGN KEY (REF_WRITER) 
REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

-- 댓글_정보공유 컬럼코멘트 생성
COMMENT ON COLUMN SHAREREPLY.REF_NO IS '댓글번호';
COMMENT ON COLUMN SHAREREPLY.BOARD_NO IS '원글번호';
COMMENT ON COLUMN SHAREREPLY.REF_WRITER IS '댓글작성자';
COMMENT ON COLUMN SHAREREPLY.REF_CONTENT IS '댓글내용';
COMMENT ON COLUMN SHAREREPLY.REF_DATE IS '댓글날짜';

-- 19. 커뮤니티 게시판_일상잡담 테이블 생성
CREATE TABLE  DAILY(
 BOARD_NO NUMBER, 
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_WRITER VARCHAR2(30) NOT NULL,
 BOARD_CONTENT VARCHAR2(2000) NOT NULL,
 BOARD_OLD_FILE VARCHAR2(100),
 BOARD_NEW_FILE VARCHAR2(100),
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER DEFAULT 0,
 LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,

  CONSTRAINT PK_DAILY_NO PRIMARY KEY (BOARD_NO),
  CONSTRAINT FK_DAILY_WRITER FOREIGN KEY (BOARD_WRITER) 
  REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);
--  커뮤니티 게시판_일상잡담 컬럼코멘트 생성
COMMENT ON COLUMN DAILY.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN DAILY.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN DAILY.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN DAILY.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN DAILY.BOARD_OLD_FILE IS '원본첨부파일명';
COMMENT ON COLUMN DAILY.BOARD_NEW_FILE IS '수정첨부파일명';
COMMENT ON COLUMN DAILY.BOARD_DATE IS '작성일자';
COMMENT ON COLUMN DAILY.BOARD_COUNT IS '게시판조회수';
COMMENT ON COLUMN DAILY.LIKE_COUNT IS '좋아요갯수';

-- 20. 댓글_일상잡담 테이블 생성
CREATE TABLE DAILYREPLY (
 REF_NO NUMBER , 
BOARD_NO NUMBER NOT NULL,
REF_WRITER VARCHAR2(30) NOT NULL,
REF_CONTENT VARCHAR2(2000) NOT NULL,
REF_DATE DATE DEFAULT SYSDATE,

CONSTRAINT PK_DAILYREPLY_NO PRIMARY KEY (REF_NO),
CONSTRAINT FK_DAILYREPLY_NO FOREIGN KEY (BOARD_NO) 
REFERENCES DAILY (BOARD_NO) ON DELETE SET NULL,
CONSTRAINT FK_DAREF_WRITER FOREIGN KEY (REF_WRITER) 
REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

-- 댓글_일상정보 컬럼코멘트 생성
COMMENT ON COLUMN DAILYREPLY.REF_NO IS '댓글번호';
COMMENT ON COLUMN DAILYREPLY.BOARD_NO IS '원글번호';
COMMENT ON COLUMN DAILYREPLY.REF_WRITER IS '댓글작성자';
COMMENT ON COLUMN DAILYREPLY.REF_CONTENT IS '댓글내용';
COMMENT ON COLUMN DAILYREPLY.REF_DATE IS '댓글날짜';

-- 21. 커뮤니티 게시판_질문 테이블 생성
CREATE TABLE  QUESTION(
 BOARD_NO NUMBER, 
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_WRITER VARCHAR2(30) NOT NULL,
 BOARD_CONTENT VARCHAR2(2000) NOT NULL,
 BOARD_OLD_FILE VARCHAR2(100),
 BOARD_NEW_FILE VARCHAR2(100),
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER DEFAULT 0,
 LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,

  CONSTRAINT PK_QUESTION_NO PRIMARY KEY (BOARD_NO),
  CONSTRAINT FK_QUESTION_WRITER FOREIGN KEY (BOARD_WRITER)
  REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

-- 커뮤니티 게시판_질문 컬럼코멘트 생성
COMMENT ON COLUMN QUESTION.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN QUESTION.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN QUESTION.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN QUESTION.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN QUESTION.BOARD_OLD_FILE IS '원본첨부파일명';
COMMENT ON COLUMN QUESTION.BOARD_NEW_FILE IS '수정첨부파일명';
COMMENT ON COLUMN QUESTION.BOARD_DATE IS '작성일자';
COMMENT ON COLUMN QUESTION.BOARD_COUNT IS '게시판조회수';
COMMENT ON COLUMN QUESTION.LIKE_COUNT IS '좋아요갯수';

-- 22. 댓글_질문답변 테이블 생성
CREATE TABLE QUESTIONREPLY (
REF_NO NUMBER, 
BOARD_NO NUMBER NOT NULL,
REF_WRITER VARCHAR2(30) NOT NULL,
REF_CONTENT VARCHAR2(2000) NOT NULL,
REF_DATE DATE DEFAULT SYSDATE,

CONSTRAINT PK_QUESTIONREPLY_NO PRIMARY KEY (REF_NO),
CONSTRAINT FK_QUESTIONREPLY_NO FOREIGN KEY (BOARD_NO) 
REFERENCES QUESTION (BOARD_NO) ON DELETE SET NULL,
CONSTRAINT FK_QREF_WRITER FOREIGN KEY (REF_WRITER) 
REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

-- 댓글_질문답변
COMMENT ON COLUMN QUESTIONREPLY .REF_NO IS '댓글번호';
COMMENT ON COLUMN QUESTIONREPLY .BOARD_NO IS '원글번호';
COMMENT ON COLUMN QUESTIONREPLY .REF_WRITER IS '댓글작성자';
COMMENT ON COLUMN QUESTIONREPLY .REF_CONTENT IS '댓글내용';
COMMENT ON COLUMN QUESTIONREPLY .REF_DATE IS '댓글날짜';


-- 23. 커뮤니티 게시판_동물일기 테이블 생성
CREATE TABLE  DIARY(
 BOARD_NO NUMBER, 
 BOARD_TITLE VARCHAR2(50) NOT NULL,
 BOARD_WRITER VARCHAR2(30) NOT NULL,
 BOARD_CONTENT VARCHAR2(2000) NOT NULL,
 BOARD_OLD_FILE VARCHAR2(100),
 BOARD_NEW_FILE VARCHAR2(100),
 BOARD_DATE DATE DEFAULT SYSDATE,
 BOARD_COUNT NUMBER DEFAULT 0,
 LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,
 OPEN CHAR(1),

  CONSTRAINT PK_DIARY_NO PRIMARY KEY (BOARD_NO),
  CONSTRAINT FK_DIARY_WRITER FOREIGN KEY (BOARD_WRITER) 
  REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);



-- 커뮤니티 게시판_동물일기 컬럼코멘트 생성
COMMENT ON COLUMN DIARY.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN DIARY.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN DIARY.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN DIARY.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN DIARY.BOARD_OLD_FILE IS '원본첨부파일명';
COMMENT ON COLUMN DIARY.BOARD_NEW_FILE IS '수정첨부파일명';
COMMENT ON COLUMN DIARY.BOARD_DATE IS '작성일자';
COMMENT ON COLUMN DIARY.BOARD_COUNT IS '게시판조회수';
COMMENT ON COLUMN DIARY.LIKE_COUNT IS '좋아요갯수';
COMMENT ON COLUMN DIARY.OPEN IS '공개여부';

-- 24. 댓글_동물일기 테이블 생성 
CREATE TABLE DIARYREPLY(
REF_NO NUMBER, 
BOARD_NO NUMBER NOT NULL,
REF_WRITER VARCHAR2(30) NOT NULL,
REF_CONTENT VARCHAR2(2000) NOT NULL,
REF_DATE DATE DEFAULT SYSDATE,

CONSTRAINT PK_DIARYREPLY_NO PRIMARY KEY (REF_NO),
CONSTRAINT FK_DIARYREPLY_NO FOREIGN KEY (BOARD_NO)
REFERENCES DIARY (BOARD_NO) ON DELETE SET NULL,
CONSTRAINT FK_DIREF_WRITER FOREIGN KEY (REF_WRITER)
REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

-- 댓글_동물일기 컬럼코멘트 생성(수정필요)
COMMENT ON COLUMN DIARYREPLY.REF_NO IS '댓글번호';
COMMENT ON COLUMN DIARYREPLY.BOARD_NO IS '원글번호';
COMMENT ON COLUMN DIARYREPLY.REF_WRITER IS '댓글작성자';
COMMENT ON COLUMN DIARYREPLY.REF_CONTENT IS '댓글내용';
COMMENT ON COLUMN DIARYREPLY.REF_DATE IS '댓글날짜';

--24. 컨테스트
CREATE TABLE CONTEST(
USER_ID VARCHAR2(30),
CONTEST_NO NUMBER PRIMARY KEY,
CONTEST_TITLE VARCHAR2(100) NOT NULL,
CONTEST_CONTENT VARCHAR2(300),
CONTEST_DATE DATE DEFAULT SYSDATE,
CONTEST_COUNT NUMBER DEFAULT 0,
LIKE_COUNT NUMBER DEFAULT 0,
CONTEST_OLDFILE VARCHAR2(30) NOT NULL,
CONTEST_NEWFILE VARCHAR2(30),
GRADE_FIRST CHAR NOT NULL,

CONSTRAINT FK_CON_WRITER FOREIGN KEY (USER_ID)
REFERENCES MEMBER (USER_ID) ON DELETE SET NULL
);

COMMENT ON COLUMN CONTEST.USER_ID IS '작성자 아이디';
COMMENT ON COLUMN CONTEST.CONTEST_NO IS '게시글 번호';
COMMENT ON COLUMN CONTEST.CONTEST_TITLE IS '게시글 제목';
COMMENT ON COLUMN CONTEST.CONTEST_CONTENT IS '게시글 내용';
COMMENT ON COLUMN CONTEST.CONTEST_DATE IS '작성 날짜';
COMMENT ON COLUMN CONTEST.CONTEST_COUNT IS '조회수';
COMMENT ON COLUMN CONTEST.LIKE_COUNT IS '좋아요 표시';
COMMENT ON COLUMN CONTEST.CONTEST_OLDFILE IS '첨부이미지';
COMMENT ON COLUMN CONTEST.CONTEST_NEWFILE IS '수정이미지';
COMMENT ON COLUMN CONTEST.GRADE_FIRST IS '1등 여부';
COMMIT;